@echo off
set STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
set STREAMLIT_SERVER_HEADLESS=true
set STREAMLIT_SERVER_PORT=8501
set STREAMLIT_GLOBAL_DISABLE_WATCHDOG=true
set STREAMLIT_CLIENT_TOOLBAR_MODE=viewer
set STREAMLIT_SERVER_ADDRESS=127.0.0.1
set STREAMLIT_EMAIL=""
python -m streamlit run app.py
